name: Contribution Tracker

on:
  schedule:
    - cron: '0 0 */14 * *' # Runs every 14 days
  workflow_dispatch: # Allows manual trigger

jobs:
  track-contributions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (optional, for GitHub CLI)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Generate Contribution Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Generating contribution report..."

        # Count commits for the last 14 days
        echo "Commits by contributors:" > contributions.txt
        git log --since="2 weeks ago" --pretty=format:"%an" | sort | uniq -c >> contributions.txt

        # Fetch pull requests merged in the last 14 days
        echo "Merged Pull Requests:" >> contributions.txt
        gh pr list --state merged --search "merged:>=2 weeks ago" --json title,author --jq '.[] | "\(.title) by \(.author.login)"' >> contributions.txt

    - name: Upload Contribution Report
      uses: actions/upload-artifact@v3
      with:
        name: contribution-report
        path: contributions.txt
