# This is a basic workflow to help you get started with Actions
name: Contribution Tracker

permissions:
  contents: read
  pull-requests: read

on:
  schedule:
    - cron: '0 0 */7 * *' # Runs every 7 days
  workflow_dispatch: # Allows manual trigger

jobs:
  track-contributions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Contribution Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Generating contribution report..."
        # Your existing script for counting commits and fetching PRs

        # Count commits for the last 7 days
        echo "Commits by contributors (last 7 days):" > contributions.txt
        git log --since="7 days ago" --pretty=format:"%an" | sort | uniq -c >> contributions.txt

        # Fetch pull requests merged in the last 7 days
        echo "Merged Pull Requests (last 7 days):" >> contributions.txt
        gh pr list --state merged --search "merged:>=7 days ago" --json title,author --jq '.[] | "\(.title) by \(.author.login)"' >> contributions.txt

    - name: Upload Contribution Report
      uses: actions/upload-artifact@v3
      with:
        name: contribution-report
        path: contributions.txt
